protocol:
  search:
    mapping:
      - beckn_key: context
        value: session
        compute: buildContext(session, action)

      - beckn_key: message.intent.category.descriptor.code
        value: session.loanCategaory

      - beckn_key: message.intent.provider.id
        value: session.providerId
      - beckn_key: message.intent.provider.items[0].id
        value: session.itemId
      - beckn_key: message.intent.provider.items[0].xinput.form.id
        value: session.formId
      - beckn_key: message.intent.provider.items[0].xinput.form_response.status
        value: session.search2FormStatus || session.search1FormStatus
      - beckn_key: message.intent.provider.items[0].xinput.form_response.submission_id
        value: session.personalInfoSubmissionId

      - beckn_key: message.intent.payment.collected_by
        value: session.paymentCollectedBy
      - beckn_key: message.intent.payment.tags
        value: session.paymentTagsSearch
        compute: buildTags(session.paymentTagsSearch)

  select:
    mapping:
      - beckn_key: context
        value: session
        compute: buildContext(session, action)

      - beckn_key: message.order.provider.id
        value: session.providerId
      - beckn_key: message.order.items[0].id
        value: session.selectItemID
      - beckn_key: message.order.items[0].parent_item_id
        value: session.parentItemId

      - beckn_key: message.order.items[0].xinput.form.id
        value: session.formIdAmountAdjustForm
      - beckn_key: message.order.items[0].xinput.form_response.status
        value: session.selectFormStatus
      - beckn_key: message.order.items[0].xinput.form_response.submission_id
        value: data.adjustAmountSubmissionId

  init:
    mapping:
      - beckn_key: context
        value: session
        compute: buildContext(session, action)

      - beckn_key: message.order.provider.id
        value: session.providerId
      - beckn_key: message.order.items[0].id
        value: session.selectItemID
      - beckn_key: message.order.items[0].parent_item_id
        value: session.parentItemId
      - beckn_key: message.order.items[0].xinput.form.id
        value: session.eMandateDetailsFormId || session.accointDetailsFormId || session.kycFormId || session.customerInfoFormId
      - beckn_key: message.order.items[0].xinput.form_response.status
        value: session.initFormStatus
      - beckn_key: message.order.items[0].xinput.form_response.submission_id
        value: session.eMandateDetailsSubmissionId || session.accointDetailsFormSubmissionId || session.kycSubmissionId || session.customerInfoSubmissionId

      - beckn_key: message.order.payments[0].id
        value: session.paymentID[0].id
      - beckn_key: message.order.payments[0].status
        value: session.paymentStatusInit1 || session.paymentStatus
      - beckn_key: message.order.payments[0].collected_by
        value: session.collectedBy
      - beckn_key: message.order.payments[0].type
        value: session.paymentType
      - beckn_key: message.order.payments[0].params.bank_code
        value: session.bankCode
      - beckn_key: message.order.payments[0].params.bank_account_number
        value: session.bankAccountNumber
      - beckn_key: message.order.payments[0].params.virtual_payment_address
        value: session.virtualPaymentAddress
      - beckn_key: message.order.payments[0].tags
        value: session.paymentTagsInit
        compute: buildTags(session.paymentTagsInit)

  confirm:
    mapping:
      - beckn_key: context
        value: session
        compute: buildContext(session, action)

      - beckn_key: message.order.provider.id
        value: session.providerId
      - beckn_key: message.order.items[0].id
        value: session.selectItemID
      - beckn_key: message.order.items[0].parent_item_id
        value: session.parentItemId
      - beckn_key: message.order.items[0].xinput.form.id
        value: session.loanAgreementFormId
      - beckn_key: message.order.items[0].xinput.form_response.status
        value: "'SUCCESS'"
      - beckn_key: message.order.items[0].xinput.form_response.submission_id
        value: session.loanAgreementSubmissionId

      - beckn_key: message.order.payments[0].id
        value: session.paymentID[0].id
      - beckn_key: message.order.payments[0].collected_by
        value: session.collectedBy
      - beckn_key: message.order.payments[0].status
        value: session.paymentStatusConfirm
      - beckn_key: message.order.payments[0].type
        value: session.paymentTypeConfirm
      - beckn_key: message.order.payments[0].params.bank_code
        value: session.bankCode
      - beckn_key: message.order.payments[0].params.bank_account_number
        value: session.bankAccountNumber
      - beckn_key: message.order.payments[0].params.virtual_payment_address
        value: session.virtualPaymentAddress
      - beckn_key: message.order.payments[0].tags
        value: session.paymentTagsConfirm
        compute: buildTags(session.paymentTagsConfirm)

  status:
    mapping:
      - beckn_key: context
        value: session
        compute: buildContext(session, action)

      - beckn_key: message.ref_id
        value: session.currentTransactionId

  update:
    mapping:
      - beckn_key: context
        value: session
        compute: buildContext(session, action)

      - beckn_key: message.update_target
        value: fulfillmentText
      - beckn_key: message.order.id
        value: data.orderId

      - beckn_key: message.order.fulfillments[0].state.descriptor.code
        value: data.fulfillmentStatus

  on_search:
    # sessionData:
    #   - business_key: "formId"
    #     extractionPath: "message.catalog.providers[].items[]{ id : xinput.form.id, itemId: id}"
    #   - business_key: "providerId"
    #     extractionPath: "message.catalog.providers[]{id: id}"
    mapping:
      - business_key: "bpp_id"
        extractionPath: context.bpp_id
      - business_key: "bpp_uri"
        extractionPath: context.bpp_uri
      - business_key: formData
        extractionPath: "message.catalog.providers[]{providerId: id}.items[]{formUrl : xinput.form.url, id : xinput.form.id, itemId: id}"
      - business_key: itemDetails
        extractionPath: "message.catalog.providers[].items[?(parent_item_id)]{itemID: id, parentItemId: parent_item_id}"
      - business_key: error
        extractionPath: error

  on_select:
    mapping:
      - business_key: providerId
        extractionPath: "message.order.provider.id"
      - business_key: formData
        extractionPath: "message.order.items[]{mimeType: xinput.form.mime_type, formUrl : xinput.form.url, id : xinput.form.id, itemId: id}"
      - business_key: error
        extractionPath: error

  on_init:
    sessionData:
      - business_key: paymentID
        extractionPath: "message.order.payments[]{id: id}"
    mapping:
      - business_key: formData
        extractionPath: "message.order.items[]{mimeType: xinput.form.mime_type, formUrl : xinput.form.url, id : xinput.form.id, itemId: id}"
      - business_key: error
        extractionPath: error

  on_confirm:
    sessionData:
      - business_key: orderId
        extractionPath: message.order.id
    mapping:
      - business_key: orderId
        extractionPath: message.order.id
      - business_key: error
        extractionPath: error

  on_status:
    mapping:
      - business_key: formData
        extractionPath: "message.order.items[]{id: xinput.form.id, status: xinput.form_response.status, submissionId:  xinput.form_response.submission_id}"
      - business_key: loanStatus
        extractionPath: "message.order.fulfillments[]{state: state.descriptor.code}"
      - business_key: error
        extractionPath: error

  on_update:
    mapping:
      - business_key: error
        extractionPath: error
