calls:
  - config: "settle"
    mode: "ASYNC"
    callback:
      config: "on_settle"
      endpoint: "mapper/ondc"
      unsolicitedEndpoint: "mapper/unsolicited"
  - config: "report"
    mode: "ASYNC"
    callback:
      config: "on_report"
      endpoint: "mapper/ondc"
      mode: "SYNC"
      unsolicitedEndpoint: "mapper/unsolicited"
  - config: "recon"
    mode: "ASYNC"
    callback:
      config: "on_recon"
      endpoint: "mapper/ondc"
      mode: "SYNC"
      unsolicitedEndpoint: "mapper/unsolicited"
