BAP:
  $ref: ./FIS/BAP/index.yaml
BPP:
  $ref: ./FIS/BPP/index_loan.yaml
schema:
  $ref: ./schema/FIS/index.yaml
attributes:
  personal-loan-flow-1:
    $ref: ./attributes/personal-loan-flow-1/index.yaml
  invoice-loan-flow-1:
    $ref: ./attributes/invoice-loan-flow-1/index.yaml
version: "1.0.0"
