calls:
  - config: "settle"
    mode: "ASYNC"
    unsolicated: false
    callback:
      config: "on_settle"
      endpoint: "mapper/ondc"
      mode: "ASYNC"
      unsolicitedEndpoint: "/settle"
  - config: "on_settle"
    mode: "ASYNC"
    callback:
      config: "report"
      endpoint: "mapper/ondc"
      mode: "ASYNC"
      unsolicitedEndpoint: "mapper/unsolicited"
  - config: "report"
    mode: "ASYNC"
    unsolicated: false
    callback:
      config: "on_report"
      endpoint: "mapper/ondc"
      mode: "ASYNC"
      unsolicitedEndpoint: "/report"
  - config: "on_report"
    mode: "ASYNC"
    callback:
      config: "recon"
      endpoint: "mapper/ondc"
      mode: "ASYNC"
      unsolicitedEndpoint: "mapper/unsolicited"
  - config: "recon"
    mode: "ASYNC"
    unsolicated: false
    callback:
      config: "on_recon"
      endpoint: "mapper/ondc"
      mode: "ASYNC"
      unsolicitedEndpoint: "/report"
  - config: "on_recon"
    mode: "ASYNC"
    callback:
      config: "on_recon"
      endpoint: "mapper/ondc"
      mode: "ASYNC"
      unsolicitedEndpoint: "mapper/unsolicited"