calls:
  - config: "issue"
    mode: "ASYNC"
    unsolicated: false
    callback:
      config: "on_issue"
      endpoint: "mapper/ondc"
      mode: "ASYNC"
      unsolicitedEndpoint: "/issue" 
  - config: "on_issue"
    mode: "ASYNC"
    callback:
      config: "on_issue"
      endpoint: "mapper/ondc"
      mode: "ASYNC"
      unsolicitedEndpoint: "mapper/unsolicited"
